import datetime
x=datetime.datetime.now()
print(x)
#The date contains year,month,day,hour,minute,second,and microsecond.
print(datetime.datetime(2023,4,16))
m=x.strftime("%Y")
print(m)
m=x.strftime("%b")
print(m)
m=x.strftime("%B")
print(m)
m=x.strftime("%M")
print(m)
m=x.strftime("%m")
print(m)
m=x.strftime("%Y")
print(m)
